/**
 * <auto-generated>
 * Generated from ui/openapi/openapi.json — do not edit by hand.
 * Run: npm run regen-api-types (after ./scripts/export_openapi.py)
 * </auto-generated>
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/v1/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies Route */
        get: operations["list_strategies_route_v1_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Strategy Route */
        get: operations["get_strategy_route_v1_strategies__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}/cash-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cash Events Route */
        get: operations["list_cash_events_route_v1_strategies__name__cash_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}/deposit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deposit Route */
        post: operations["deposit_route_v1_strategies__name__deposit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}/withdraw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw Route */
        post: operations["withdraw_route_v1_strategies__name__withdraw_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}/set-starting-bankroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Starting Bankroll Route */
        post: operations["set_starting_bankroll_route_v1_strategies__name__set_starting_bankroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Route */
        post: operations["pause_route_v1_strategies__name__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Route */
        post: operations["resume_route_v1_strategies__name__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}/set-kelly-fraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Kelly Route */
        post: operations["set_kelly_route_v1_strategies__name__set_kelly_fraction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/strategies/{name}/decommission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decommission Route */
        post: operations["decommission_route_v1_strategies__name__decommission_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System Route */
        get: operations["get_system_route_v1_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause System Route */
        post: operations["pause_system_route_v1_system_pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume System Route */
        post: operations["resume_system_route_v1_system_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit Route */
        get: operations["list_audit_route_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources Route */
        get: operations["list_sources_route_v1_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Signals Route */
        get: operations["list_signals_route_v1_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Positions Route */
        get: operations["list_positions_route_v1_positions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Eval Route */
        get: operations["list_eval_route_v1_eval_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eval/{strategy}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Eval Route */
        get: operations["get_eval_route_v1_eval__strategy__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** AmountReasonBody */
        AmountReasonBody: {
            /** Amountcents */
            amountCents?: number | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * AuditActor
         * @enum {string}
         */
        AuditActor: "user" | "system" | "scheduler";
        /** AuditEvent */
        AuditEvent: {
            /** Id */
            id: string;
            /** Occurredat */
            occurredAt: string;
            actor: components["schemas"]["AuditActor"];
            /** Action */
            action: string;
            /** Targettype */
            targetType: string;
            /** Targetid */
            targetId: string;
            /** Beforestate */
            beforeState: {
                [key: string]: unknown;
            };
            /** Afterstate */
            afterState: {
                [key: string]: unknown;
            };
            /** Reason */
            reason: string;
            /** Requestid */
            requestId: string;
        };
        /** CalibrationBin */
        CalibrationBin: {
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
            /** Predictedmean */
            predictedMean: number;
            /** Observedfreq */
            observedFreq: number;
            /** Count */
            count: number;
        };
        /** CashEvent */
        CashEvent: {
            /** Id */
            id: string;
            /** Strategyname */
            strategyName: string;
            /** Occurredat */
            occurredAt: string;
            kind: components["schemas"]["CashEventKind"];
            /** Amountcents */
            amountCents: number;
            /** Balanceaftercents */
            balanceAfterCents: number;
            /** Reason */
            reason: string;
            /** Refpositionid */
            refPositionId: string | null;
        };
        /**
         * CashEventKind
         * @enum {string}
         */
        CashEventKind: "deposit" | "withdraw" | "realized_pnl" | "fee" | "transfer_in" | "transfer_out";
        /** EvalRosterEntry */
        EvalRosterEntry: {
            /** Strategyname */
            strategyName: string;
            /** Ntrades */
            nTrades: number;
            /** Hitrate */
            hitRate?: number | null;
            /** Brierscore */
            brierScore?: number | null;
            /** Pnlcents */
            pnlCents: number;
            /** Posterioredgecilow */
            posteriorEdgeCiLow?: number | null;
        };
        /** EvalSnapshot */
        EvalSnapshot: {
            /** Window */
            window: string;
            /** Computedat */
            computedAt: string;
            /** Ntrades */
            nTrades: number;
            /** Nwins */
            nWins: number;
            /** Hitrate */
            hitRate?: number | null;
            /** Brierscore */
            brierScore?: number | null;
            /** Logloss */
            logLoss?: number | null;
            /** Pnlcents */
            pnlCents: number;
            /** Sharpeproxy */
            sharpeProxy?: number | null;
            /** Maxdrawdowncents */
            maxDrawdownCents: number;
            /** Posterioredgemean */
            posteriorEdgeMean: number;
            /** Posterioredgecilow */
            posteriorEdgeCiLow: number;
            /** Posterioredgecihigh */
            posteriorEdgeCiHigh: number;
            /** Calibrationbins */
            calibrationBins: components["schemas"]["CalibrationBin"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthzResponse */
        HealthzResponse: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /** Version */
            version: string;
            /** Git Sha */
            git_sha: string;
            /** Request Id */
            request_id: string;
            /** Checked At */
            checked_at: string;
            /** Db Shared */
            db_shared: string;
            /** Db Per Env */
            db_per_env: string;
            scheduler_cycle?: components["schemas"]["SchedulerCycleHealth"] | null;
        };
        /** PaperPositionRecord */
        PaperPositionRecord: {
            /** Id */
            id: string;
            /** Strategyname */
            strategyName: string;
            /** Ticker */
            ticker: string;
            side: components["schemas"]["PositionSide"];
            /** Openedat */
            openedAt: string;
            /** Closedat */
            closedAt?: string | null;
            /** Openavgprice */
            openAvgPrice: number;
            /** Qty */
            qty: number;
            /** Costbasiscents */
            costBasisCents: number;
            /** Realizedpnlcents */
            realizedPnlCents?: number | null;
            /** Unrealizedpnlcents */
            unrealizedPnlCents?: number | null;
            /** Status */
            status: string;
        };
        /**
         * PositionSide
         * @enum {string}
         */
        PositionSide: "yes" | "no";
        /** ReasonBody */
        ReasonBody: {
            /** Reason */
            reason: string;
        };
        /** SchedulerCycleHealth */
        SchedulerCycleHealth: {
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "ok" | "error";
            /** Last Error */
            last_error?: string | null;
            /** Last Cycle At */
            last_cycle_at?: string | null;
            /** Last Success At */
            last_success_at?: string | null;
        };
        /** SetKellyBody */
        SetKellyBody: {
            /** Fraction */
            fraction: number;
            /** Reason */
            reason: string;
        };
        /** SetStartingBankrollBody */
        SetStartingBankrollBody: {
            /** Amountcents */
            amountCents: number;
            /** Reason */
            reason: string;
        };
        /**
         * SignalOutcome
         * @enum {string}
         */
        SignalOutcome: "order_placed" | "rejected_kelly_zero" | "rejected_exposure_cap" | "rejected_correlation_cap" | "rejected_below_threshold" | "rejected_below_min_position" | "rejected_market_closed" | "rejected_stale_inputs" | "rejected_system_paused" | "rejected_already_positioned";
        /** SignalRecord */
        SignalRecord: {
            /** Id */
            id: string;
            /** Strategyname */
            strategyName: string;
            /** Ticker */
            ticker: string;
            /** Evaluatedat */
            evaluatedAt: string;
            /** Probyes */
            probYes: number;
            /** Confidence */
            confidence: number;
            /** Featuressnapshot */
            featuresSnapshot?: {
                [key: string]: unknown;
            } | null;
            /** Marketstate */
            marketState?: {
                [key: string]: unknown;
            } | null;
            outcome: components["schemas"]["SignalOutcome"];
            /** Rejectionreason */
            rejectionReason?: string | null;
        };
        /** SourceHealthEntry */
        SourceHealthEntry: {
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            /** Status */
            status?: string | null;
            /** Lastrunat */
            lastRunAt?: string | null;
            /** Lastsuccessat */
            lastSuccessAt?: string | null;
            /** Rowslastrun */
            rowsLastRun?: number | null;
            /** Lasterror */
            lastError?: string | null;
        };
        /** StrategyConfig */
        StrategyConfig: {
            /** Minbankrollcents */
            minBankrollCents: number;
            /** Mintradeablebankrollcents */
            minTradeableBankrollCents: number;
            /** Maxdrawdownpctfromhwm */
            maxDrawdownPctFromHwm: number;
            /** Autoresumeondeposit */
            autoResumeOnDeposit: boolean;
            /** Maxinputageseconds */
            maxInputAgeSeconds: number;
            /** Confidencefloor */
            confidenceFloor?: number | null;
            /** Disagreementthreshold */
            disagreementThreshold?: number | null;
            /** Spreadmarginmultiplier */
            spreadMarginMultiplier?: number | null;
            /** Widespreadthreshold */
            wideSpreadThreshold?: number | null;
            /** Exposurecappct */
            exposureCapPct?: number | null;
            /** Correlationcappct */
            correlationCapPct?: number | null;
            /** Minedge */
            minEdge?: number | null;
            /** Maxdisagreementf */
            maxDisagreementF?: number | null;
        };
        /** StrategyEval */
        StrategyEval: {
            /** Strategyname */
            strategyName: string;
            /** Windows */
            windows: components["schemas"]["EvalSnapshot"][];
        };
        /** StrategyInstance */
        StrategyInstance: {
            /** Name */
            name: string;
            /** Enabled */
            enabled: boolean;
            state: components["schemas"]["StrategyState"];
            /** Bankrollcents */
            bankrollCents: number;
            /** Bankrollhwmcents */
            bankrollHwmCents: number;
            /** Initialdepositcents */
            initialDepositCents: number;
            /** Kellyfraction */
            kellyFraction: number;
            config: components["schemas"]["StrategyConfig"];
            /** Laststatechangeat */
            lastStateChangeAt: string;
            /**
             * Todaypnlcents
             * @default 0
             */
            todayPnlCents: number;
        };
        /**
         * StrategyState
         * @enum {string}
         */
        StrategyState: "seeded" | "active" | "low_bankroll_paused" | "drawdown_paused" | "operator_paused" | "decommissioned";
        /** SystemEnvState */
        SystemEnvState: {
            state: components["schemas"]["SystemState"];
            /** Killswitchreason */
            killSwitchReason: string | null;
            /** Killswitchtrippedat */
            killSwitchTrippedAt: string | null;
        };
        /**
         * SystemState
         * @enum {string}
         */
        SystemState: "active" | "paused";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    list_strategies_route_v1_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyInstance"][];
                };
            };
        };
    };
    get_strategy_route_v1_strategies__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyInstance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cash_events_route_v1_strategies__name__cash_events_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deposit_route_v1_strategies__name__deposit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmountReasonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    withdraw_route_v1_strategies__name__withdraw_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AmountReasonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CashEvent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_starting_bankroll_route_v1_strategies__name__set_starting_bankroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetStartingBankrollBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyInstance"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    pause_route_v1_strategies__name__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_route_v1_strategies__name__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_kelly_route_v1_strategies__name__set_kelly_fraction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetKellyBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decommission_route_v1_strategies__name__decommission_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_system_route_v1_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemEnvState"];
                };
            };
        };
    };
    pause_system_route_v1_system_pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_system_route_v1_system_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReasonBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_route_v1_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                before?: string | null;
                actor?: string | null;
                action?: string | null;
                target_type?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_route_v1_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceHealthEntry"][];
                };
            };
        };
    };
    list_signals_route_v1_signals_get: {
        parameters: {
            query?: {
                strategy_name?: string | null;
                ticker?: string | null;
                outcome?: string | null;
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_positions_route_v1_positions_get: {
        parameters: {
            query?: {
                strategy_name?: string | null;
                status?: string | null;
                limit?: number;
                before?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaperPositionRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_route_v1_eval_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRosterEntry"][];
                };
            };
        };
    };
    get_eval_route_v1_eval__strategy__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyEval"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
}
